import Accueil from "@/components/accueil";
import ContactForm from "@/components/contact";
import Footer from "@/components/footer";
import Header from "@/components/header";
import Produits from "@/components/produits";
import Video from "@/components/video";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="">
        <Accueil />
        <Produits />
        <Video />
        <ContactForm />
        <Footer />
      </main>
    </>
  );
}
